# Generated by Django 3.1.6 on 2021-02-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_auto_20210209_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='items',
            new_name='item',
        ),
    ]
