# Generated by Django 3.1.6 on 2021-02-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_auto_20210209_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.TextField(default='SOME STRING', max_length=300),
        ),
    ]
