# Generated by Django 3.1.6 on 2021-02-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0005_auto_20210226_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='completed',
        ),
    ]
